Move common functions into debian/common, fix bug where script wouldn't run bzr-buildpackage

diff --git a/debian/common b/debian/common
--- a/debian/common
+++ b/debian/common
@@ -63,3 +63,71 @@ function mapKdeCodeToIbusPkg {
       eval "$1=\"\"";;
   esac
 }
+
+if [ ! -x /usr/bin/bzr-buildpackage ]; then
+  echo "bzr-buildpackage needs to be installed to build kde-l10n packages"
+  exit 1
+fi
+
+if ! source debian/config-l10n ; then
+    echo "could not source config!!"
+    exit 1
+fi
+
+clean_dld=1
+subset=""
+
+for arg in "$@"
+do
+    case "$arg" in
+    -ncd)
+      clean_dld=0
+      ;;
+    *)
+      subset="$subset $arg"
+    esac
+done
+
+WDIR=`pwd`
+case ${WDIR##*/} in
+  "debian" )
+    cd ..;;
+  "build" )
+    cd ..;;
+  "kde-l10n-common" )
+    ;;
+esac
+
+
+BOILERPLATE="# ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !#\n# DO NOT EVEN THINK ABOUT CHANGING THIS FILE DIRECTLY! ! ! !\n# PLEASE USE THE BZR BRANCH AS SEEN IN debian\/control\n# MAKE YOUR CHANGES THERE AND THEN RUN debian\/build-l10n.sh\n# kthxbai :)\n################################################################################\n################################################################################\n################################################################################\n################################################################################"
+
+if [[ `bzr revno` != `bzr revno ${BRANCH}` ]]; then
+  echo "For one reason or another the parent branch does not match the local one, please ensure they match, or all is going down the drain."
+  echo "Most importantly: YOU MUST PUSH TO THE PARENT BRANCH BEFORE BUILDING THE PACKAGES!!!"
+  echo "Leaving you alone in the cold."
+  exit 1
+fi
+
+if [ -e build ]; then
+  echo "A already existing build/ directory was found, which indicates that there was a build done earlier."
+  echo "Note: you can also run this script with -ncd to preserve only the tar.xz files from build/."
+  echo "Do you REALLY REALLY want to mess with the current build dir? (y/n)"
+  read -e reply
+  if [[ $reply != "y" ]]; then
+    echo "bye!"
+    exit 0
+  fi
+fi
+
+# clean build dir
+if [ $clean_dld -eq 0 ]; then
+  find build/* -maxdepth 0 | grep -v build-area | xargs rm -rfv
+  find build/build-area/* -maxdepth 0 | grep -v ".tar.xz" | xargs rm -rfv
+else
+  rm -rvf build
+  mkdir build
+fi
+
+cd build
+WDIR=`pwd`
+
